export const createUsers = `CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  role VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  age VARCHAR(50) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  guardianPhone VARCHAR(50),
  guardianName VARCHAR(255),
  father_name VARCHAR(255),
  subject_id VARCHAR(50) NULL,
  profile VARCHAR(500),
  issue TEXT NULL,
  issue_level ENUM('low', 'medium', 'high') DEFAULT 'low',
  class VARCHAR(100),
  grade VARCHAR(100) NOT NULL,
  gender VARCHAR(50) NOT NULL,
  city VARCHAR(100),
  academic_year VARCHAR(9) NOT NULL DEFAULT (YEAR(CURRENT_DATE)),
  prevClassDocument VARCHAR(500),
  annual_fee DECIMAL(10,2) NULL,
  remaining_fee DECIMAL(10,2) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
`;
